name: Generate README.md File

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */4 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Bun Runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.0.0"
      - name: Install Dependencies
        run: bun install --production
      - name: Generate README.md File
        run: bun run index.ts
        env:
          WEATHER_LONGITUDE: ${{ secrets.WEATHER_LONGITUDE }}
          WEATHER_LATITUDE: ${{ secrets.WEATHER_LATITUDE }}
          WAKATIME_JSON_EMBED_URL: ${{ secrets.WAKATIME_JSON_EMBED_URL }}
          HOMELAB_API_URL: ${{ secrets.HOMELAB_API_URL }}
          YHYPE_TRACKER_URL: "https://hit.yhype.me/github/profile?user_id=69585766"
          TIMEZONE: "Europe/Berlin"
      - uses: EndBug/add-and-commit@v9
        with:
          add: "README.md"
          message: "Generated `README.md`"
          default_author: "github_actions"
