name: Generate README.md File

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "30 */3 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Bun Runtime
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.0.0"
      - name: Install Dependencies
        run: bun install --frozen-lockfile --production
      - name: Generate README.md File
        run: bun run index.ts
        env:
          PERSONAL_API_TOKEN: ${{ secrets.PERSONAL_API_TOKEN }}
          YHYPE_TRACKER_URL: "https://hit.yhype.me/github/profile?user_id=69585766"
      - uses: EndBug/add-and-commit@v9
        with:
          add: "README.md"
          message: "Generated `README.md`"
          default_author: "github_actions"
